using CollectionManager.Models;
using CollectionManager.tools;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.IdentityModel.Tokens;
using static System.Net.Mime.MediaTypeNames;

//Author: Dustin Gregerson
//Date: 11/29/2023
//Description: handels the routing for the items
namespace CollectionManager.Controllers
{
    public class ItemController : Controller
    {
        private CollectersContext context;
        public ItemController(CollectersContext ctx)
        {
            context = ctx;
        }

        public IActionResult Delete(string id)
        {
            //finds the item that was clicked on by the user in the user details list
            //the asp-rout-id is set to the id of the item next to the button in the list
            Item item=context.items.Find(int.Parse(id));
            context.Remove(item);
            context.SaveChanges();
            return RedirectToAction("details", "User");
        }
        public ViewResult List(string filterBy,string value)
        {
            List<ItemsToUsersList> list = new List<ItemsToUsersList>();
            List<string> tags= new List<string>();
            List<string> userNames= new List<string>();
            List<string> itemNames= new List<string>();
            //this quary grabs all the tags by there grouped tag name
            var tagsResult = from item in context.items
                         join user in context.users on item.userID equals user.userID
                         group item by item.tag into groupedItems
                         select new { itemTags = groupedItems.Key};
            //this loop stores all the tags in a list
            foreach(var row in tagsResult)
            {
                tags.Add(row.itemTags);
            }
            //this quary grabs all the items by there grouped item name
            var itemNamesResult = from item in context.items
                         join user in context.users on item.userID equals user.userID
                         group item by item.Name into groupedItems
                         select new { itemNames = groupedItems.Key };
            //this loop stores all the item names into a list
            foreach (var row in itemNamesResult)
            {
                itemNames.Add(row.itemNames);
            }
            //this quary grabs all the user names grouped by the user names
            var userNamesResult = from item in context.items
                              join user in context.users on item.userID equals user.userID
                              group user by user.userName into groupedItems
                              select new { userNames = groupedItems.Key };
            //this list stores the user names
            foreach (var row in userNamesResult)
            {
                userNames.Add(row.userNames);
            }
            //the tags, user names, and item names are stored in the view bag for, this is so they
            //can be used to filter the items in the list by the tag, user name or the item name
            ViewBag.tags= tags;
            ViewBag.userNames= userNames;
            ViewBag.itemNames= itemNames;

            //this checks if list is generated by the user clicking a filter button or by clicking item collection
            //link in the nav bar
            if (filterBy == null)
            {
                //joins items to users and then stores the columns that are need to display the information
                //about the item on the list.cshtml page
                var result1 = from item in context.items
                             join user in context.users on item.userID equals user.userID
                             select new { ItemName = item.Name, ItemDescription = item.Description, ItemTag = item.tag, UserName = user.userName, ItemPic = item.image, ItemId = item.itemID };
                
                //this loops stores each row result into the ItemsToUsersList model that is passed to the
                //list view
                foreach (var row in result1)
                {
                    ItemsToUsersList item = new ItemsToUsersList();
                    item.name = row.ItemName;
                    item.description = row.ItemDescription;
                    item.tag = row.ItemTag;
                    item.userName = row.UserName;
                    item.itemId = "" + row.ItemId;
                    item.pic = imageConverter.byteArrayTo64BaseEncode(row.ItemPic);
                    list.Add(item);
                }

                return View(list);
            }
            else
            {
                //This switched is used to display diffrent items in the list based off what filter
                //the user has selected. the value is the selected btn item in the drop down list
                switch (filterBy)
                {
                    case "name":
                        //finds all items that have name that is equal to the value
                        var result2 = from item in context.items
                                     join user in context.users on item.userID equals user.userID
                                     where item.Name==value
                                     select new { ItemName = item.Name, ItemDescription = item.Description, ItemTag = item.tag, UserName = user.userName, ItemPic = item.image, ItemId = item.itemID };
                        //fills the model with the quaryed result and passes it to the view
                        foreach (var row in result2)
                        {
                            ItemsToUsersList item = new ItemsToUsersList();
                            item.name = row.ItemName;
                            item.description = row.ItemDescription;
                            item.tag = row.ItemTag;
                            item.userName = row.UserName;
                            item.itemId = "" + row.ItemId;
                            item.pic = imageConverter.byteArrayTo64BaseEncode(row.ItemPic);
                            list.Add(item);
                        }
                        return View(list);
                    case "tag" :
                        //finds all items that have a tag that is equal to the value
                        var result3 = from item in context.items
                                     join user in context.users on item.userID equals user.userID
                                     where item.tag == value
                                     select new { ItemName = item.Name, ItemDescription = item.Description, ItemTag = item.tag, UserName = user.userName, ItemPic = item.image, ItemId = item.itemID };
                        //fills the model with the result and passes it to the view
                        foreach (var row in result3)
                        {
                            ItemsToUsersList item = new ItemsToUsersList();
                            item.name = row.ItemName;
                            item.description = row.ItemDescription;
                            item.tag = row.ItemTag;
                            item.userName = row.UserName;
                            item.itemId = "" + row.ItemId;
                            item.pic = imageConverter.byteArrayTo64BaseEncode(row.ItemPic);
                            list.Add(item);
                        }
                        return View(list);
                    case "userName":
                        //finds all items that have username name that is equal to the value
                        var result4 = from item in context.items
                                      join user in context.users on item.userID equals user.userID
                                      where user.userName == value
                                      select new { ItemName = item.Name, ItemDescription = item.Description, ItemTag = item.tag, UserName = user.userName, ItemPic = item.image, ItemId = item.itemID };
                        //fills the model with the quaryed result and passes it to the view
                        foreach (var row in result4)
                        {
                            ItemsToUsersList item = new ItemsToUsersList();
                            item.name = row.ItemName;
                            item.description = row.ItemDescription;
                            item.tag = row.ItemTag;
                            item.userName = row.UserName;
                            item.itemId = "" + row.ItemId;
                            item.pic = imageConverter.byteArrayTo64BaseEncode(row.ItemPic);
                            list.Add(item);
                        }
                        return View(list);
                        //this section returns every item
                    default:
                        
                        var result5 = from item in context.items
                                     join user in context.users on item.userID equals user.userID
                                     select new { ItemName = item.Name, ItemDescription = item.Description, ItemTag = item.tag, UserName = user.userName, ItemPic = item.image, ItemId = item.itemID };

                        foreach (var row in result5)
                        {
                            ItemsToUsersList item = new ItemsToUsersList();
                            item.name = row.ItemName;
                            item.description = row.ItemDescription;
                            item.tag = row.ItemTag;
                            item.userName = row.UserName;
                            item.itemId = "" + row.ItemId;
                            item.pic = imageConverter.byteArrayTo64BaseEncode(row.ItemPic);
                            list.Add(item);
                        }

                        return View(list);
                }
            }
        }
        [HttpGet]
        public IActionResult Detailed(string id)
        {

            //checks to see if the id is set
            if(id == null)
            {
                return RedirectToAction("List", "Item");
            }
            else
            {
                //this quary finds the item with the item id of ID
                int ID=int.Parse(id);
                var result = from item in context.items
                             join user in context.users on item.userID equals user.userID
                             where item.itemID == ID
                             select new { ItemName = item.Name, ItemDescription = item.Description, ItemTag = item.tag, UserName = user.userName, ItemPic = item.image, ItemId = item.itemID };

                ItemsToUsersList itemsToUsersList = new ItemsToUsersList();
                //fills the model with the one row returned
                foreach (var row in result)
                {
                    itemsToUsersList.name = row.ItemName;
                    itemsToUsersList.description = row.ItemDescription;
                    itemsToUsersList.tag = row.ItemTag;
                    itemsToUsersList.userName = row.UserName;
                    itemsToUsersList.itemId = "" + row.ItemId;
                    itemsToUsersList.pic = imageConverter.byteArrayTo64BaseEncode(row.ItemPic);
                }

                return View(itemsToUsersList);
            }
        }
        public ViewResult Add()
        {
            //creates the error model and returns the add view
            Error error = new Error();
            return View("Add",error);
        }

        [HttpPost]
        public IActionResult AddItem() {
                Item item = new Item();
                //gets the item information from the from
                string itemName = HttpContext.Request.Form["addName"];
                string itemDescription = HttpContext.Request.Form["addDescription"];
                IFormFile itemImage = HttpContext.Request.Form.Files["addPic"];
                string itemTag = HttpContext.Request.Form["addTag"];
                string userId = HttpContext.Session.GetString("id");

                int error = 0;
                //validation for all fields
                if (itemName.Equals(""))
                {
                    error += 0x1;
                }
                if (itemDescription.Equals(""))
                {
                    error += 0x2;
                }
                if (itemImage==null)
                {
                    error += 0x4;
                }
                if(itemTag.Equals(""))
                {
                    error += 0x8;
                }
                //if error has not occured
            if (error == 0&&userId!=null)
            {
                //checks to see if the user exists in the data set as long as the user is logged in it
                //should otherwise the user is redirected to the login page
                User user = context.users.Find(int.Parse(userId));
                if (user != null)
                {
                    
                    //creats a memory stream to read the image date
                    MemoryStream memoryStream = new MemoryStream();
                    itemImage.CopyTo(memoryStream);
                    //writes the image data to the data array
                    byte[] data = memoryStream.ToArray();
                    //filling out the item
                    item.image = data;
                    item.tag = itemTag;
                    item.Name= itemName;
                    item.user= user;
                    item.Description = itemDescription;
                    item.userID = int.Parse(userId);
                    //adding the item to the data set
                    context.items.Add(item);
                    //updating the data set
                    context.SaveChanges();
                    //redirect to the users collection items
                    return RedirectToAction("details", "User");
                }
                else
                {
                    return RedirectToAction("login","User");
                }
            }
            else
            {
                //return the add page and show the errors that occured while the user was attempting to add the
                //item to the data set
                Error errorNum = new Error();
                errorNum.errorNumber= error;
                return View("Add",errorNum);
            }
        }
        //The edit action is used to edit the logged in users item
        [HttpPost]
        public IActionResult Edit(string id)
        {
            //gets the item information from the from
            string name = HttpContext.Request.Form["editName"];
            string description = HttpContext.Request.Form["editDescription"];
            IFormFile image = HttpContext.Request.Form.Files["editPic"];
            string tag = HttpContext.Request.Form["editTag"];
            int index = int.Parse(id);
            //grabbing the item from the data set
            Item item=context.items.Find(index);

            //if the item exsists this chain of if statments check to see what information the user changed
            //and assigns the changed data to the items model
            if (item != null)
            {
                if (!name.IsNullOrEmpty())
                {
                    item.Name = name;
                }
                if (!description.IsNullOrEmpty())
                {
                    item.Description = description;
                }
                if (!tag.IsNullOrEmpty())
                {
                    item.tag = tag;
                }
                if (image != null)
                {
                    MemoryStream memoryStream= new MemoryStream();
                    image.CopyTo(memoryStream);
                    byte[] data = memoryStream.ToArray();
                    item.image = data;
                }
                //update the items data set with the item
                context.SaveChanges();
            }

            //this redirects to items detailed. the new {id=id} fills out the id parameter of the Detailed IAction
            //so the user can see the changes they are makeing each time they hit submit
            return RedirectToAction("Detailed", "Item",new { id=id });
        }
    }
}
